import type { Metadata } from 'next';
import { Abril_Fatface, Geist } from 'next/font/google';
import './globals.css';
import { Provider } from './provider/root-provider';

const geistSans = Geist({
   variable: '--font-geist-sans',
   subsets: ['latin'],
});

const abrilFatface = Abril_Fatface({
   weight: '400',
   subsets: ['latin'],
   variable: '--font-abril-fatface',
});

export const metadata: Metadata = {
   title: 'ANote',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="ko">
         <body className={`${geistSans.variable} ${abrilFatface.variable}  antialiased `}>
            <Provider>{children}</Provider>
         </body>
      </html>
   );
}
